//
//  BroBump.h
//  ProjectName
//
//  Created by AuthorName on 4/30/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BroBump : NSObject

// Drawing Methods
+ (void)drawSperated_handsCanvasWithTop: (CGFloat)top;

@end
